ndl_kotenseki_layout:
  config_path: 'src/ndl_kotenseki_layout/models/ndl_kotenseki_layout_config.py'
  checkpoint_path: 'src/ndl_kotenseki_layout/models/ndl_kotenseki_layout_ver3.pth'
  device: 'cuda:0'
  'score_thr': 0.001
text_kotenseki_recognition:
  saved_preprocessor_model: 'src/text_kotenseki_recognition/model-ver2/trocr-base-preprocessor'
  saved_tokenize_model: 'src/text_kotenseki_recognition/model-ver2/decoder-roberta-v3'
  saved_ocr_model: 'src/text_kotenseki_recognition/model-ver2/kotenseki-trocr-honkoku-ver2'
  accept_empty: True
  batch_size: 16
  device: 'cuda:0'
kotenseki_reading_order:
  checkpoint_path: 'src/kotenseki_reading_order/models/kotenseki_reading_order_model.joblib'
